### ISSUE TITLE
Discussion and Suggestion issue!

### ISSUE THREAD

**Issue by SarveshDevrukhkar** [HirraZahid/FA21-bcs-139#1]
## Hello HirraZahid👋🏽,
I think you are doing great!🌟 and this is a suggestion issue.

I was going through my GitHub Profile and followers list, I found your profile.
Just for the sake of curiosity, I was going through your profile, and I found this active repository.

I see that you have done many small projects as assignments, but I can't see those anywhere so I would like to suggest that you deploy your all small project assignments somewhere, on platforms like `vercel` `netlify` etc. wherever you like.

Additionally, and can you edit your GitHub profile information, please? Because in case someone wants to connect with you then there is no option like `LinkedIn` `X` `Email` etc. and there is no `README.md` to know more that's why.

:warning: `If you have something to say on this then you can connect on LinkedIn else you can discuss more by moving this issue to the discussion section.`

**Thank You, All the best! :smile:**

**Comment by HirraZahid** [comment]
Hello sarvesh
Thanks sarvesh for you suggestion. i will definitely improve these
things.here is my linkedin profile
https://www.linkedin.com/in/hirra-z-3aa1b5245/. Have a nice day

**Comment by HirraZahid** [comment]
Thanks for your suggestion i will definitely improve these things
